language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm install
  - npm install -g parcel-bundler

script:
  - parcel build ./hello.js
  - echo "hongyun16855" | docker login -u "rope" --password-stdin
  - docker build -t mufengsm/travis-ci:latest .
  - docker push mufengsm/travis-ci:latest
